import { SearchProvider } from './context/SearchContect'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SearchProvider>
        <body>{children}</body>
      </SearchProvider>
    </html>
  );
}
